<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2014 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Admin\Controller;

use Zend\Json\Json;
use Zend\Mvc\MvcEvent;

abstract class ApiAbstractController extends BaseController
{
    protected $response, $request, $entityId;

    public function onDispatch(MvcEvent $e)
    {
        // setting entity id, response & request fields
        $this->request = $this->getRequest();
        $this->response = $this->getResponse();
        $this->entityId = (int) $this->params()->fromRoute('id', 0);
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    protected function checkMethod($method) {
        // checking method
        if($method !== $this->request->getMethod()) {
            $this->set405();
            return false;
        } else {
            return true;
        }
    }

    private function set405($message = 'Method is not allowed') {
        $this->response->setStatusCode(405);
        $this->response->setContent(Json::encode(array('message' => $message)));
    }

    protected function set404($message = 'Record not found') {
        $this->response->setStatusCode(404);
        $this->response->setContent(Json::encode(array('message' => $message)));
    }

    protected function set403($message = 'This method is restricted') {
        $this->response->setStatusCode(404);
        $this->response->setContent(Json::encode(array('message' => $message)));
    }
}
